---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dallastourtravel/public_html/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
