---
deployment:
  tasks:
    - export DEPLOYPATH=/home/daly1882/public_html/
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp dist/artikel.html $DEPLOYPATH
    - /bin/cp dist/galeri.html $DEPLOYPATH
    - /bin/cp dist/tentang-dallas.html $DEPLOYPATH
    - /bin/cp dist/syarat-ketentuan.html $DEPLOYPATH
    - /bin/cp dist/kebijakan-privasi.html $DEPLOYPATH
    - /bin/cp dist/404.shtml $DEPLOYPATH
    - /bin/cp -R dist/haji $DEPLOYPATH
    - /bin/cp -R dist/umroh $DEPLOYPATH
    - /bin/cp -R dist/wisata-halal $DEPLOYPATH
    - /bin/cp -R dist/css $DEPLOYPATH
    - /bin/cp -R dist/js $DEPLOYPATH
    - /bin/cp -R dist/assets $DEPLOYPATH
